### PR TITLE
Remove unused method `RDoc::Require#top_level` that always raises NoMethodError

### PR DESCRIPTION
**Pull request by tompng**
It has been broken since 2d884240 (Move global parse state to RDoc::Store) removed TopLevel.all_files_hash and TopLevel.all_files.

Result of `RDoc::Require.new('a','b').top_level` is basically unchanged.
Before: `NoMethodError(undefined method 'all_files_hash')`
After: `NoMethodError(undefined method 'top_level')`

### CODE REVIEW

File: lib/rdoc/code_object/require.rb [hunk 1]
```diff
@@ -16,7 +16,6 @@ class Require < CodeObject
     def initialize(name, comment)
       super()
       @name = name.gsub(/'|"/, "") #'
```
Comment (st0012) [inline lib/rdoc/code_object/require.rb]: Not related, but does the `#'` here does anything?

**Review by st0012 — APPROVED** [review]

File: lib/rdoc/code_object/require.rb (hunk 1 above)
Comment (tompng) [reply lib/rdoc/code_object/require.rb]: Removed.
It's strange. There's two more `#'` comments in `lib/rdoc/context.rb` 🤔

Comment (kou) [reply lib/rdoc/code_object/require.rb]: It's for broken syntax highlighting implementations. (e.g. Regular expression based implementation.)

If developers don't use these implementations, we can remove it.
