### PR TITLE
Fix `NoMethodError` for `tokens_to_s` method

### PR DESCRIPTION
**Pull request by toshimaru**
Calling `tokens_to_s` gets an error if `token_stream` is nil:

```
undefined method `compact' for nil:NilClass (NoMethodError)
```

So, fall back to an empty array if `@token_stream` is `nil`.

## The case `token_stream` is nil

```rb
> rdoc_method.inspect
=> "#<RDoc::AnyMethod:0x5b090 AbstractController::Translation#l (public) (alias for localize)>"
> rdoc_method.token_stream
=> nil
```

### CODE REVIEW

**Comment by toshimaru** [comment]
@nobu thanks for fixing issue caused by this change. 🙏 
72897d3

**Comment by jonathanhefner** [comment]
This seems like a breaking change, as demonstrated by https://github.com/rails/sdoc/pull/346.

`token_stream` is part of the public API, and now returns a different value when the method source is unavailable.

It is easy to handle this change in SDoc, but I wanted to point it out.
